- apt:
    name: "{{item}}"
    state: present
  with_items:
    - git
    - sqlite3
    - ruby-sqlite3
    - libsqlite3-dev
    - libssl-dev
    - gcc
    - make
    - g++
    - supervisor

- name: remove the base ruby package if installed
  apt: name={{item}} state=absent
  with_items:
    - ruby

- script: setup-ruby.sh
  become: yes

- apt:
    name: "{{item}}"
    state: present
  with_items:
    - postgresql
    - libpq-dev
  when: pwpush_db == 'postgres'
